// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE 
    (
        $1::text IS NULL OR 
        email ILIKE '%' || $1::text || '%' OR
        first_name ILIKE '%' || $1::text || '%' OR
        last_name ILIKE '%' || $1::text || '%' OR
        phone_number ILIKE '%' || $1::text || '%'
    )
    AND ($2::user_role IS NULL OR role = $2)
    AND ($3::boolean IS NULL OR is_active = $3)
    AND ($4::boolean IS NULL OR is_verified = $4)
`

type CountUsersParams struct {
	Search     pgtype.Text  `json:"search"`
	Role       NullUserRole `json:"role"`
	IsActive   pgtype.Bool  `json:"is_active"`
	IsVerified pgtype.Bool  `json:"is_verified"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.Search,
		arg.Role,
		arg.IsActive,
		arg.IsVerified,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    first_name,
    last_name,
    phone_number,
    role
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, email, first_name, last_name, phone_number, role, is_active, is_verified, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
	Role         UserRole    `json:"role"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Role        UserRole           `json:"role"`
	IsActive    bool               `json:"is_active"`
	IsVerified  bool               `json:"is_verified"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Role,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, phone_number, role, is_active, is_verified, last_login_at, created_at, updated_at
FROM users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Role        UserRole           `json:"role"`
	IsActive    bool               `json:"is_active"`
	IsVerified  bool               `json:"is_verified"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Role,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, first_name, last_name, phone_number, role, is_active, is_verified, last_login_at, created_at, updated_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Role        UserRole           `json:"role"`
	IsActive    bool               `json:"is_active"`
	IsVerified  bool               `json:"is_verified"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Role,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT id, email, password_hash, role, is_active
FROM users
WHERE email = $1 LIMIT 1
`

type GetUserForAuthRow struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         UserRole    `json:"role"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) GetUserForAuth(ctx context.Context, email string) (GetUserForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserForAuth, email)
	var i GetUserForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    id, email, first_name, last_name, phone_number, role, is_active, is_verified, last_login_at, created_at, updated_at
FROM users
WHERE
    (
        $3::text IS NULL OR 
        email ILIKE '%' || $3::text || '%' OR
        first_name ILIKE '%' || $3::text || '%' OR
        last_name ILIKE '%' || $3::text || '%' OR
        phone_number ILIKE '%' || $3::text || '%'
    )
    AND ($4::user_role IS NULL OR role = $4)
    AND ($5::boolean IS NULL OR is_active = $5)
    AND ($6::boolean IS NULL OR is_verified = $6)
ORDER BY
    CASE WHEN $7::text = 'created_at' AND $8::boolean = true THEN created_at END DESC,
    CASE WHEN $7::text = 'created_at' AND $8::boolean = false THEN created_at END ASC,
    CASE WHEN $7::text = 'email' AND $8::boolean = true THEN email END DESC,
    CASE WHEN $7::text = 'email' AND $8::boolean = false THEN email END ASC,
    CASE WHEN $7::text = 'first_name' AND $8::boolean = true THEN first_name END DESC,
    CASE WHEN $7::text = 'first_name' AND $8::boolean = false THEN first_name END ASC,
    created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit      int32        `json:"limit"`
	Offset     int32        `json:"offset"`
	Search     pgtype.Text  `json:"search"`
	Role       NullUserRole `json:"role"`
	IsActive   pgtype.Bool  `json:"is_active"`
	IsVerified pgtype.Bool  `json:"is_verified"`
	OrderBy    string       `json:"order_by"`
	IsDesc     bool         `json:"is_desc"`
}

type ListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Role        UserRole           `json:"role"`
	IsActive    bool               `json:"is_active"`
	IsVerified  bool               `json:"is_verified"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Role,
		arg.IsActive,
		arg.IsVerified,
		arg.OrderBy,
		arg.IsDesc,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Role,
			&i.IsActive,
			&i.IsVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
